name: VPS deploy
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@master

    - name: Push files
      uses: SamKirkland/FTP-Deploy-Action@master 
      with:
        server: 51.141.69.113
        server-dir: /var/www/html/
        username: ftp
        password: ${{ secrets.vps_ftp_password }}
        port: 21
        protocol: ftp      
      
      
